[package]
name = "keyzen_data"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
keyzen_core.workspace = true
serde.workspace = true
ron.workspace = true
anyhow.workspace = true
